//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanProcessingSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MortgageDbEntities : DbContext
    {
        public MortgageDbEntities()
            : base("name=MortgageDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDetail> AdminDetails { get; set; }
        public virtual DbSet<EnquiryTable> EnquiryTables { get; set; }
        public virtual DbSet<LoanForm> LoanForms { get; set; }
        public virtual DbSet<StatusTrack> StatusTracks { get; set; }
        public virtual DbSet<UserRegister> UserRegisters { get; set; }
    }
}
