//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanProcessingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoanForm()
        {
            this.StatusTracks = new HashSet<StatusTrack>();
        }
    
        public int ApplicationId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public Nullable<decimal> PhoneNo { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string PropertyType { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ImageUrl { get; set; }
        public string Status { get; set; }
        public Nullable<int> InspectorId { get; set; }
    
        public virtual AdminDetail AdminDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusTrack> StatusTracks { get; set; }
    }
}
