//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanProcessingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusTrack
    {
        public int StatusId { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AuthorityId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Status { get; set; }
    
        public virtual AdminDetail AdminDetail { get; set; }
        public virtual LoanForm LoanForm { get; set; }
        public virtual UserRegister UserRegister { get; set; }
    }
}
